# Generated by Django 6.0.2 on 2026-04-25 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.PositiveIntegerField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('terms', models.TextField(blank=True, help_text='Optional terms and milestones agreed upon by the client and freelancer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_client', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_freelancer', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='jobs.job')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='proposals.proposal')),
            ],
        ),
    ]
