# Generated by Django 6.0.2 on 2026-04-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_initial_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_project_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_paid_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
