# Generated by Django 6.0.2 on 2026-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_first_project_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume (PDF)', null=True, upload_to='resumes/'),
        ),
    ]
